### ISSUE TITLE
Unable to configure allowed elements with HTML.AllowedElements

### ISSUE THREAD

**Issue by x86demon** [xemlock/htmlpurifier-html5#12]
Hi. HTMLPurifier can not be configured with list of allowed elements
Next code produce exception
`User Warning: Element 'picture' is not supported (for information on implementing this, see the support forums)`
 
```php
$config = \HTMLPurifier_HTML5Config::createDefault();
$config->set('HTML.AllowedElements', ['img', 'picture']);
$config->set('HTML.AllowedAttributes', ['img.srcset', 'img.src', 'img.sizes']);

$htmlPurifier = new \HTMLPurifier($config);
$htmlPurifier->purify($value);
```

**Comment by xemlock** [comment]
After investigation it turned out that when you set `HTML.*` keys `HTMLPurifier_Config::set()` [removes any previously initialized HTML definition](https://github.com/ezyang/htmlpurifier/blob/d85d39d/library/HTMLPurifier/Config.php#L376), effectively removing definitions for HTML5 elements.

The fix (or rather an override for this behavior) is on its way, until it happens please setup HTML5 config with options array, like this:

```php
$config = \HTMLPurifier_HTML5Config::create([
  'HTML.AllowedElements' => ['img', 'picture'],
  'HTML.AllowedAttributes' => ['img.srcset', 'img.src', 'img.sizes'],
]);
```

Please note that the support for `sizes` attribute on `img` element is not yet released (it's currently only on `master` branch).
