### ISSUE TITLE
Question: How to add custom tags

### ISSUE THREAD

**Issue by dkrnl** [xemlock/htmlpurifier-html5#28]
Hi!

When i try this code:
```php
 $config = HTMLPurifier_HTML5Config::create($initial);
 $definition = $config->getHTMLDefinition(true);
 $definition->addElement("oembed", "Inline", "Inline", "", []);
```
Throwed exception:

> Message: Cannot retrieve raw definition after it has already been setup (try moving this code block earlier in your initialization)
From: .../vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php 
Line: 540

thx

**Comment by xemlock** [comment]
Hi @dkrnl,
~~There is no easy way to do it at the moment, unfortunately. That's a feature I totally overlooked. But I should come up with a working solution by the end of this week.~~

Edit: After some investigation it turned out that I was wrong. You can do it like this:

```php
require './vendor/autoload.php';

$initial = HTMLPurifier_HTML5Config::createDefault();
$config = HTMLPurifier_HTML5Config::create($initial);
$config->set('HTML.DefinitionID', 'CustomHTML5');
$config->set('HTML.DefinitionID', 1);

$def = $config->maybeGetRawHTMLDefinition();
if ($def) {
    $def->addElement('oembed', 'Inline', 'Inline', '', []);
}

$purifier = new HTMLPurifier($config);
echo $purifier->purify('<span><oembed>Foo</oembed></span>');
```

What is important, is that when you add new element definitions, you must provide a new values for `HTML.DefinitionID` and `HTML.DefinitionRev`, unique for a given batch of changes. Or just disable definition cache (probably not a good idea) by calling:

```php
$config->set('Cache.DefinitionImpl', null);
```

**Comment by dkrnl** [comment]
@xemlock thank you for reply.

When i try `$config->set("Cache.DefinitionImpl", null);` my code working well, but have some performance issues, but it is not important... :-)

And one moment:
```php
$def = $config->maybeGetRawHTMLDefinition();
if ($def) {
    $def->addElement('oembed', 'Inline', 'Inline', '', []);
} else {
   // loaded serialized config from cache?
}
```

**Comment by xemlock** [comment]
Nope. You don't need the `else` branch, because `$def` will be `null` if the HTML definition used by the config is already set up and loaded from cache.

If you're not using cache you will always enter the `if` branch.
