### ISSUE TITLE
Question: Figure not working?

### ISSUE THREAD

**Issue by goby1986** [xemlock/htmlpurifier-html5#29]
Installed via composer:
```
composer require ezyang/htmlpurifier
composer require xemlock/htmlpurifier-html5
```
 
I have this code:
```php
Debug("START", 'comment_xss');
Debug($_POST['comment'], 'comment_xss');			
$config = \HTMLPurifier_HTML5Config::create([
	  'HTML.AllowedElements' => ['p', 'figure', 'img', 'picture'],
	  'HTML.AllowedAttributes' => ['img.srcset', 'img.src', 'img.sizes'],
]);
$purifier = new \HTMLPurifier($config);
$comment = $purifier->purify($_POST['comment']);						
Debug($comment, 'comment_xss');
```
Here are the logs(Debug):
```
2018-12-17 16:04:10 START;
2018-12-17 16:04:10 <figure><img src="https://bla_bla.jpg" data-image="5236469657"></figure><p>aa</p>; 
2018-12-17 16:04:10 <p>aa</p>
```

As you can see the entire `<figure>` is removed even if I've added it in the AllowedElements array.
What am I doing wrong? Can you please help?

**Comment by xemlock** [comment]
Hi @goby1986,
You're getting this output, because by default HTML Purifier removes invalid `<img>` tags.

In your example the `<img>` tag has invalid `src` attribute (underscores are not allowed in hostnames by default). And after removing its only child, the empty `<figure>` gets removed as well.

If you provide a valid hostname (or an empty string) to `src` attribute, then the `<figure>` and `<img>` tags pass the purification process.

As a side note:
- `Core.RemoveInvalidImg` setting controls removal of invalid `<img>` tags (`true` by default)
- `Core.AllowHostnameUnderscore` setting controls whether underscore should be allowed in hostnames (`false` by default)

**Comment by goby1986** [comment]
Hi 
Thanks for the reply! Is there a way to disable that setting to make it allow img src with underscore?

**Comment by goby1986** [comment]
:D Nevermind,
I've fixed the problem:
```
$config = \HTMLPurifier_HTML5Config::create([
  'HTML.AllowedElements' => ['p', 'figure', 'img', 'picture'],
  'HTML.AllowedAttributes' => ['img.srcset', 'img.src', 'img.sizes'],
  'Core.AllowHostnameUnderscore' => true
]);
```
Thank you for your help!
