### ISSUE TITLE
Create a Laravel version

### ISSUE THREAD

**Issue by ghost** [xemlock/htmlpurifier-html5#49]
Would it be possible to create a cloned repo with a Facades for laravel users?

**Comment by xemlock** [comment]
Hi @ayumihamsaki,

Writing integrations for frameworks, whether it be Laravel, Symfony, ZF or any other, is outside of the scope of this project. So I'd rather recommend creating an issue (or PR) in their repos (for Laravel I believe it would be [mews/purifier](https://github.com/mewebstudio/Purifier) or [stevebauman/purify](https://github.com/stevebauman/purify)) with request to make them accept custom config class (but still inheriting from `HTMLPurifier_Config`).

I think writing yet another package that offers the same functionality as already available ones, is not a good idea. Especially when the only difference would be just using `HTMLPurifier_HTML5Config` instead of `HTMLPurifier_Config`.

**Comment by ghost** [comment]
@xemlock No problem, I will open an issue with mews and recommend them to add your package.
