### ISSUE TITLE
tr@bgcolor removed

### ISSUE THREAD

**Issue by bytestream** [xemlock/htmlpurifier-html5#53]
htmlpurifier has support for deprecated attributes and will convert them to their `style` equivalent
```html
<table>
<tr bgcolor="#edeeef">
<td width="3"></td>
<td bgcolor="#f9fafa" width="1"></td>
<td bgcolor="#edeeef" width="1"></td>
<td bgcolor="#dbdee0" width="1"></td>
</tr></table>
```

When using this lib bgcolor seems to get nuked. I've tried added `"HTML.TidyLevel"            => "heavy",` but it doesn't seem to do anything. http://htmlpurifier.org/docs/enduser-tidy.html makes reference to the doctype, so I'm wondering whether the HTML5 doctype has something to do with it not working?

**Comment by bytestream** [comment]
https://github.com/ezyang/htmlpurifier/pull/244

**Comment by xemlock** [comment]
The legacy module was explicitly disabled for `HTML5` doctype. But now I think it should be possible to enable it via a configuration (see #32).

**Comment by bytestream** [comment]
Ah I see. That's why it's getting removed. 

I'm not sure that there's any specific benefit to enabling the Legacy module vs using the Tidy option? Though there does seem to be a few warnings in the comments that tidy may cause the HTML to display differently.

**Comment by xemlock** [comment]
Without changes to this lib codebase Tidy won't work for HTML5 doctype at all, because there are no legacy attributes defined (because the `Legacy` module which defines them is not loaded). So HTMLPurifier logic will treat all legacy attributes (such as `td@bgcolor`) as incorrect and will remove them before Tidy modules kick in and do their job.

Contrary to what I thought earlier, now I think it would be useful if the Tidy functionality was available for HTML5 doctype too.
